#! /bin/sh

if [ -e /home/admin/AlcheMist/miner/access_code ]; then
    cp /home/admin/AlcheMist/miner/access_code /tmp
fi
if [ -e /home/admin/AlcheMist/miner/asic.ini ]; then
    cp /home/admin/AlcheMist/miner/asic.ini /tmp
fi



rm /home/admin/old_AlcheMist
mv /home/admin/AlcheMist /home/admin/old_AlcheMist
cp -r /tmp/AlcheMist /home/admin

if [ -e /tmp/asic.ini ]; then
    cp /tmp/asic.init /home/admin/AlcheMist/miner
fi

sleep 3
touch /tmp/Good_luck

/sbin/reboot